# Generated by Django 5.2.3 on 2025-07-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_role_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="google_login",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
