# Generated by Django 5.2.3 on 2025-07-01 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_google_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(help_text="User's role determining their permissions", on_delete=django.db.models.deletion.RESTRICT, related_name='role', to='users.role'),
        ),
    ]
