# Generated by Django 5.2.3 on 2025-07-02 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.ForeignKey(
                default=3,
                help_text="User's role determining their permissions",
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="role",
                to="users.role",
            ),
        ),
    ]
