# Generated by Django 5.2.4 on 2025-07-17 05:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.JSONField(
                blank=True, help_text="User's physical address", null=True
            ),
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.TextField()),
                ("company_email", models.EmailField(max_length=254)),
                ("company_address", models.JSONField()),
                (
                    "company_phone",
                    models.CharField(
                        help_text="User's contact phone number",
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("brand", models.TextField(blank=True, null=True)),
                ("pcode", models.TextField(blank=True, null=True)),
                ("gst_no", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
