# Generated by Django 5.2.4 on 2025-07-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_vendor_company_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
