# Generated by Django 5.2.4 on 2025-07-18 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_vendor_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vendor",
            old_name="status",
            new_name="is_approved",
        ),
    ]
