# Generated by Django 5.2.4 on 2025-07-18 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_rename_status_vendor_is_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendor",
            name="is_approved",
        ),
    ]
