# Generated by Django 5.2.4 on 2025-07-18 06:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_remove_vendor_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="company_name",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="company_phone",
            field=models.CharField(
                help_text="User's contact phone number",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
    ]
