# Generated by Django 5.2.4 on 2026-02-25 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_newslettersubscription_trainingregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorContactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_ids', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_click_log', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
