services:
  - type: web
    name: mheback
    env: python
    region: oregon

    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: |
      python manage.py migrate --noinput
      gunicorn mhe_backend.wsgi:application --bind 0.0.0.0:$PORT --workers 4

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: false  # Should be false in production
      - key: DJANGO_SETTINGS_MODULE
        value: mhe_backend.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_v5G8jRgcxYnN@ep-falling-term-aez544hh-pooler.c-2.us-east-2.aws.neon.tech/new_mhe_neon?sslmode=require&channel_binding=require
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: ENVIRONMENT
        value: production