# Generated by Django 5.2.3 on 2025-06-20 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_banner_reviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="stars",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
