# Generated by Django 5.2.4 on 2025-07-31 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0014_merge_20250730_0419"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blog_title", models.CharField(max_length=100)),
                ("image1", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True, null=True)),
                ("meta_title", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "description1",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("blog_url", models.CharField(max_length=200, unique=True)),
                ("tags", models.CharField(blank=True, max_length=100, null=True)),
                ("author_name", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "blog_category",
                    models.ForeignKey(
                        help_text="Blog category",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blogCategory",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "db_table": "blog_blog",
            },
        ),
    ]
