# Generated by Django 5.2.4 on 2025-07-31 10:02

import blogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_alter_blog_image1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image1",
            field=models.ImageField(max_length=500, upload_to=blogs.models.blog_path),
        ),
    ]
