# Generated by Django 5.2.4 on 2025-07-30 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
        ("products", "0014_merge_20250730_0419"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="image2",
        ),
        migrations.AlterField(
            model_name="blog",
            name="blog_category",
            field=models.ForeignKey(
                help_text="Blog category",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blogCategory",
                to="products.category",
            ),
        ),
    ]
