# Generated by Django 5.2.3 on 2025-06-23 09:53

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="banner",
        ),
        migrations.RemoveField(
            model_name="category",
            name="prod_image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="prod_image",
        ),
        migrations.RemoveField(
            model_name="product",
            name="prod_images",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="banner",
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="prod_image",
        ),
        migrations.AddField(
            model_name="category",
            name="cat_banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=products.models.category_image_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="cat_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=products.models.category_image_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="sub_banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=products.models.subcategory_image_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="sub_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=products.models.subcategory_image_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brochure",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=products.models.product_brochure_upload_path,
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=products.models.product_image_upload_path
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
