# Generated by Django 5.2.3 on 2025-06-30 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="dimensions",
        ),
        migrations.RemoveField(
            model_name="product",
            name="weight",
        ),
    ]
