# Generated by Django 5.2.3 on 2025-06-25 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_category_banner_remove_category_prod_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="product_details",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="product_details",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_details",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
