# Generated by Django 5.2.4 on 2025-07-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('rental', 'Rental')], default='new', help_text='Product condition type', max_length=70),
        ),
    ]
