# Generated by Django 5.2.4 on 2025-07-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='direct_sale',
            field=models.BooleanField(default=False, help_text='Whether product is available for direct sale'),
        ),
        migrations.AddField(
            model_name='product',
            name='online_payment',
            field=models.BooleanField(default=False, help_text='Whether product is available for online payment'),
        ),
    ]
