# Generated by Django 5.2.4 on 2025-07-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_direct_sale_product_online_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('rental', 'Rental'), ('attachments', 'Attachments')], default='new', help_text='Product condition type', max_length=70),
        ),
    ]
