# Generated by Django 5.2.4 on 2025-07-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hide_price',
            field=models.BooleanField(default=False, help_text='Whether product price should be hidden'),
        ),
    ]
