# Generated by Django 5.2.4 on 2025-07-24 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_product_rejection_reason_product_status"),
        ("products", "0009_wishlist_updated_at"),
    ]

    operations = []
