# Generated by Django 5.2.4 on 2025-07-25 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_merge_20250724_1453'),
        ('products', '0010_merge_20250724_1633'),
    ]

    operations = [
    ]
