# Generated by Django 5.2.4 on 2025-07-28 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_merge_20250726_0007"),
        ("products", "0011_merge_20250726_1226"),
    ]

    operations = []
