# Generated by Django 5.2.4 on 2025-07-28 12:28

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_merge_20250728_0953"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                max_length=500, upload_to=products.models.product_image_upload_path
            ),
        ),
    ]
