# Generated by Django 5.2.4 on 2025-07-29 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_merge_20250727_0923'),
        ('products', '0013_alter_productimage_image'),
    ]

    operations = [
    ]
