# Generated by Django 5.2.4 on 2025-08-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_merge_20250730_0419"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="product",
            name="products_pr_type_043e11_idx",
        ),
        migrations.RemoveField(
            model_name="product",
            name="type",
        ),
        migrations.AddField(
            model_name="product",
            name="types",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="A list of product types (e.g., ['new', 'rental'])",
            ),
        ),
    ]
