# Generated by Django 5.2.4 on 2025-08-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_remove_product_products_pr_type_043e11_idx_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="types",
            new_name="type",
        ),
    ]
