# Generated by Django 5.2.4 on 2025-09-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0016_rename_types_product_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="company_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="email",
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="full_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="phone",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="rental",
            name="address",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="rental",
            name="email",
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="rental",
            name="full_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="rental",
            name="phone",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
