# Generated by Django 5.2.4 on 2026-07-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_quote_user_alter_rental_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.FileField(blank=True, null=True, upload_to='product_offers/'),
        ),
    ]
