# Generated by Django 5.2.4 on 2026-07-24 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_offer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('offer', 'Offer'), ('brochure', 'Brochure')], max_length=10)),
                ('file_name', models.CharField(max_length=255)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_downloads', to='products.product')),
                ('user', models.ForeignKey(help_text='Logged-in user who downloaded the document', on_delete=django.db.models.deletion.CASCADE, related_name='document_downloads', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(help_text='Vendor who owns the product (product.user at download time)', on_delete=django.db.models.deletion.CASCADE, related_name='product_document_downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-downloaded_at'],
                'indexes': [models.Index(fields=['vendor'], name='products_do_vendor__75d2e7_idx'), models.Index(fields=['user'], name='products_do_user_id_7b911a_idx'), models.Index(fields=['product'], name='products_do_product_7fbaa3_idx'), models.Index(fields=['downloaded_at'], name='products_do_downloa_817668_idx')],
            },
        ),
    ]
