# Generated by Django 5.2.4 on 2026-08-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_documentdownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('external_leads', 'External Leads')], default='website', max_length=20),
        ),
        migrations.AddField(
            model_name='rental',
            name='source',
            field=models.CharField(choices=[('website', 'Website'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('external_leads', 'External Leads')], default='website', max_length=20),
        ),
    ]
